### ISSUE TITLE
sunpy-soar not available in conda-forge

### ISSUE THREAD

**Issue by herroyalmaj** [sunpy/sunpy-soar#123]
### Describe the bug

(soar_env) hmiddleton@ESAC01106057 my_utilities % conda install -c conda-forge sunpy_soar   
Retrieving notices: ...working... done
Channels:
 - conda-forge
Platform: osx-64
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - sunpy_soar

Current channels:

  - https://conda.anaconda.org/conda-forge

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

### To Reproduce

See above. From https://docs.sunpy.org/projects/soar/ thought it should be available.

**Comment by Cadair** [comment]
Hi @herroyalmaj thanks for the issue.

sunpy-soar is on conda-forge, I think maybe you need `sunpy-soar` not `sunpy_soar`?

**Comment by nabobalis** [comment]
Yeah, unfortunately the package is named with a `-` but the import is `_`

**Comment by herroyalmaj** [comment]
Just going from https://docs.sunpy.org/projects/soar/

**Comment by nabobalis** [comment]
That also should not happen.

**Comment by nabobalis** [comment]
This is on conda forge or on pypi?

**Comment by herroyalmaj** [comment]
The first link under 'Getting Help' on https://docs.sunpy.org/projects/soar/

**Comment by herroyalmaj** [comment]
Thank you!

**Comment by nabobalis** [comment]
If you enoutcher anything else, just let us know and we can fix it!
