### ISSUE TITLE
What data products are already duplicated with the VSO?

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy-soar#25]
### Provide a general description of the issue or problem.

The VSO is already indexing some of the SOAR archive, this issue is to keep track of what products are and are not also downloadable through the VSO.

From speaking to Ed, I know that the EUI data are already accessible (without the ability to search on Level), if anyone knows anything else please let us know.

**Comment by ejm4567** [comment]
EUI is currently available via the VSO. We are also currently working on making SPICE available via the VSO as well.

**Comment by dstansby** [comment]
I'm going to close this as I'm not sure the value of tracking what the VSO serves belongs here - the goal of `sunpy-soar` is to provide access to everything on the SOAR, and any coordination above that should be done somewhere else (perhaps at the SunPy ecosystem level).

**Comment by dstansby** [comment]
> Users being able to see when they might need to use sunpy-soar vs being able to use the VSO is valuable documentation in my mind.

Fair point. In that case I think an explanation along these lines best put in the README of this pacakge (which is also the docs for this package), and that's the action needed to close this issue.
