### ISSUE TITLE
Update README changelog section for 1.3

### ISSUE THREAD

**Issue by dstansby** [sunpy/sunpy-soar#29]
### Describe the bug

-

### To Reproduce

import sunpy

sunpy.map.Map(...)
etc

**Comment by nabobalis** [comment]
Is it worth having the changelog in the readme?

**Comment by dstansby** [comment]
For a small package like this where all the docs are in the README, I think it's valuable having it there.

**Comment by nabobalis** [comment]
See if https://github.com/sunpy/sunpy-soar/pull/30 is good enough.
