### ISSUE TITLE
Support for low latency (LL) data level

### ISSUE THREAD

**Issue by jgieseler** [sunpy/sunpy-soar#31]
### Describe the feature

Because `sunpy_soar` interprets data `level` as an integer (e.g., `level = a.Level(1)`), it doesn't support low latency data. 

SOAR has multiple processing levels: L0, L1, L2, L3, LL01, LL02, LL03 (cf. http://soar.esac.esa.int/soar/#search or https://issues.cosmos.esa.int/solarorbiterwiki/display/SOSP/SOAR+%28Solar+Orbiter+Archive%29+-+How+to+Use#SOAR(SolarOrbiterArchive)HowtoUse-machine_interface). Right now, only the first 4 "normal" levels (L0, L1, L2, L3) are supported by `sunpy_soar`; those starting with LL (for low latency) not. Even though this data product is probably not demanded that much, I think it might be worthwhile to integrate this option, especially because it shouldn't be too complicated.

### Proposed solution

As far as I understand it, this would not only need changes in sunpy_soar/attrs.py: https://github.com/sunpy/sunpy-soar/blob/55549bc86287ba20b59906c1a608658c5212f596/sunpy_soar/attrs.py#L96-L99
But also somewhere in the search because it right now seems to omit low latency results. The following search provides 0 results, while on http://soar.esac.esa.int/soar/#search some LL02 data files are found:
``` python
>>> import sunpy_soar
>>> from sunpy.net import Fido
>>> from sunpy.net import attrs as a
>>> import datetime as dt

>>> time = a.Time(dt.date(2022, 3, 13), dt.date(2022, 3, 14))
>>> instrument = a.Instrument('MAG')
>>> Fido.search(instrument & time)
<sunpy.net.fido_factory.UnifiedResponse object at 0x7f530c549ab0>
Results from 1 Provider:

0 Results from the SOARClient:

Instrument Data product Level Start time End time Filesize
                                                   Mbyte  
---------- ------------ ----- ---------- -------- --------

```

**Comment by dstansby** [comment]
👍 this should definitely be supported.

I am pro omitting low-latency results unless they are explicitly requested (and documenting this decison in the README).

In terms of implementing this, I'm not sure how to do it because the [Level attribute](https://docs.sunpy.org/en/stable/generated/api/sunpy.net.attrs.Level.html?highlight=level#sunpy.net.attrs.Level) in sunpy doesn't support arbitrary strings. Perhaps @Cadair has thoughts on implementation?

**Comment by Cadair** [comment]
> the [Level attribute](https://docs.sunpy.org/en/stable/generated/api/sunpy.net.attrs.Level.html?highlight=level#sunpy.net.attrs.Level) in sunpy doesn't support arbitrary strings

yes it does?

**Comment by dstansby** [comment]
Okay, I think I misread the docstring for the level attribute. In that case I suggest that we accept:
- Integer values that are interpreted as not low level (current behaviour)
- String values of the form "L{number}" or "LL{number}", and we strip the "L"s, cast number part to int, then construct one of L0, L1, L2, L3, LL01, LL02, LL03 to pass to the query

**Comment by jgieseler** [comment]
That sounds reasonable. :+1:
