### ISSUE TITLE
a.soar.Product information 

### ISSUE THREAD

**Issue by hayesla** [sunpy/sunpy-soar#33]
### Describe the feature

When using the `a.soar.Product` attrs, it would be nice to be able to find out the available product identifiers (i.e. `EUI-FSI174-IMAGE`,  `MAG-RTN-BURST` etc), in particular by using the tab autocomplete like with other aspects of Fido attrs. 

Not entirely sure how this could be done? Anyone any ideas, happy to work on it.

**Comment by hayesla** [comment]
I've just asked Helen from SOAR to find out

**Comment by dstansby** [comment]
This should definitely be doable by querying via TAP (see https://github.com/sunpy/sunpy-soar/issues/32), I'm currently taking a stab at it

**Comment by hayesla** [comment]
Great!
