### ISSUE TITLE
Make `_is_datasource_for` a lot more specific

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy-soar#35]
### Describe the bug

The soar client is very trigger happy on saying it can service a client at the moment. Ideally it would only return `True` from `_is_datasource_for` if it has a good chance of returning data.

### To Reproduce

import sunpy

sunpy.map.Map(...)
etc

**Comment by dstansby** [comment]
Can you give an example query where `_is_datasource_for` should return `False`, but currently doesn't?

**Comment by Cadair** [comment]
Ah I have just been told the behaviour I noticed a few days ago was actually a server issue.

I do wonder if the list of allowed levels should be done in `_is_datasource_for` that gives the user less feedback, but is a pattern we have used before.

**Comment by dstansby** [comment]
Given the lack of reproducible example I'm going to close this. If there's an example of a query that `_is_datasource_for` returns `True` when it returns `False`, please open a new issue
