### ISSUE TITLE
Updating to sunpy_soar==1.5 issue

### ISSUE THREAD

**Issue by hayesla** [sunpy/sunpy-soar#54]
### Describe the bug

I just updated to the latest release (1.5) and get the following error:

```python
>>> import sunpy_soar
FileNotFoundError: [Errno 2] No such file or directory: '/Users/laura.hayes/opt/miniconda3/lib/python3.9/site-packages/sunpy_soar/data/attrs.json'

```
when downgrading to 1.4, this is not an issue. Maybe something to do with release yesterday?

**Comment by dstansby** [comment]
Ahhhhh thanks for reporting, just seen this in the conda build too. I'm guessing the new `attrs.json` file isn't being packaged, will take a look now.

**Comment by dstansby** [comment]
@hayesla is this working for you now? I'm still seeing issues on conda, but I think this should be fixed in the pypi pacakge...

**Comment by dstansby** [comment]
Sigh, I don't think I fixed it right

**Comment by dstansby** [comment]
Sigh, is it working now in 1.5.2? I've tested the PyPi release locally and it seems to, but will let you close this issue yourself once you've checked it's fixed 😄

**Comment by hayesla** [comment]
working now - thanks @dstansby !
