### ISSUE TITLE
Adopt Tox and Other SunPy packaging tools

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy-soar#58]
### Describe the bug

This is now a sponsored package, so it should be using all the same testing and development tools as all the other sponsored packages. Until I spend the time on the package template, this is still a manual process.

If someone wants to get to this in the next few weeks then great, otherwise I will probably use this as the first test out of the updated package template.

### To Reproduce

import sunpy

sunpy.map.Map(...)
etc

**Comment by hayesla** [comment]
I guess this is now fixed with #95 right @nabobalis ?

**Comment by nabobalis** [comment]
Yeah!
