### ISSUE TITLE
Add some more docs - readthedocs?

### ISSUE THREAD

**Issue by hayesla** [sunpy/sunpy-soar#85]
As more features are now available (e.g. query SOOP), and with a plan to add more info from different tables I think some documentation would help

I think we should build a readthedocs for sunpy_soar

### Proposed solution

do it

**Comment by wtbarnes** [comment]
Given #84 and the proposed additions in #66 and #46, I think this is needed. The simple documentation in the README will quickly become insufficient as the amount of functionality here grows. However, if we are ultimately going to merge this into `sunpy`, I'm less inclined to have a separate docs page that we have to maintain.

**Comment by wtbarnes** [comment]
From #85

> Following the SunPy affiliated package review, I mentioned that some more documentation about the package would be useful. In particular more documentation regarding some higher level stuff about the the client interacts with the SOAR which would be useful for future developers. It would also be nice to have some more examples on how to use sunny-soar.
