### ISSUE TITLE
SOAR 1.11 has breaking changes

### ISSUE THREAD

**Issue by hayesla** [sunpy/sunpy-soar#93]
### Describe the bug

The SOAR has updated and has changed all the product names to lowercase meaning that the products here dont work anymore (as all registered as capitalised).

There may be other changes too, I'll look into it now and update

### To Reproduce
``` python 
# Create search attributes
instrument = a.Instrument('EUI')
time = a.Time('2021-02-01', '2021-02-02')
level = a.Level(1)
product = a.soar.Product.eui_fsi304_image

# Do search
result = Fido.search(instrument & time & a.Level(1) & product)
print(result)
Results from 1 Provider:

0 Results from the SOARClient:

Instrument Data product Level Start time End time Filesize SOOP Name
                                                   Mbyte            
---------- ------------ ----- ---------- -------- -------- ---------


```

**Comment by jgieseler** [comment]
Let me know if I can help, as our code is partly relying on sunpy-soar.

By the way, where can one see the current changes to SOAR? https://www.cosmos.esa.int/web/soar/release-notes only has v1.9.0 (24 January 2023) listed. It would actually be handy to know of such changes in advance; is there some kind of SOAR mailing list?

**Comment by hayesla** [comment]
I'll make a PR by this afternoon, thanks Jan! Yeah I'm chasing it down on the ESA side, it looks like its just these are the updated features:

• Enhance data download options
• new asynchronous data download button
• data download up to 50GB
• enable TAP downloads from data items
• enhanced user interface notifications for download limits
• Upgrade to TAP 9.0.4
• Support searching for active/inactive science products
• Process start and end dates from JP2 files metadata
• Conversion of CDF and FITS descriptors to lower case

The last point is the breaking point here. I'll ask them to put it on the SOAR site too.

**Comment by ebuchlin** [comment]
[Release notes](https://www.cosmos.esa.int/web/soar/release-notes) have been updated.

However, a [query for all file descriptors](http://soar.esac.esa.int/soar-sl-tap/tap/sync?REQUEST=doQuery&LANG=ADQL&FORMAT=json&QUERY=SELECT+DISTINCT+descriptor+FROM+soar.v_sc_data_item) shows that there are still some files with the old upper case descriptors (such as "SPICE-N-RAS"), I guess this will be corrected soon.

**Comment by hayesla** [comment]
thanks for flagging that @ebuchlin , yeah looks like theres some files that are still using the capitalised descriptor (only for SPICE it seems?):

```
name : number of files
spice-n-exp : 32234
SPICE-N-EXP : 1262
spice-n-ras : 14456
SPICE-N-RAS : 470
spice-n-ras-int : 6
spice-n-sit : 646
SPICE-N-SIT : 21
spice-w-exp : 3044
SPICE-W-EXP : 402
spice-w-ras : 1408
SPICE-W-RAS : 8
spice-w-sit : 60
SPICE-W-SIT : 2
```

I'll follow this up with Helen at the SOAR

**Comment by ebuchlin** [comment]
It looks like the capitalised descriptors have gone now.

**Comment by herroyalmaj** [comment]
Hi, 
Sorry, the left over capital descriptors were orphan records and have been removed. Thanks for dealing with this and I will be sure to let you know of any other changes well in advance.
Thanks, H
